language: java
script: "ant dist -Dversion=$TRAVIS_BUILD_NUMBER"
jdk:
  - oraclejdk8

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://${GITHUB_KEY}@github.com/AbeelLab/genometools --tags




deploy:
  provider: releases
  api_key: "${GITHUB_KEY}"
  file_glob: true
  file: "*.zip"s
  skip_cleanup: true
  on:
    tags: false
    
branches:
  except:
    - /^*-[0-9]+/